# Generated by Django 3.0.7 on 2020-06-23 16:14

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscriber',
            managers=[
                ('objects', authentification.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
