# Generated by Django 3.0.7 on 2020-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20200623_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
