# Generated by Django 3.0.7 on 2020-06-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='patient',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
