# Generated by Django 3.0.7 on 2020-06-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_auto_20200625_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfile',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='examen.Examen'),
        ),
    ]
