# Generated by Django 3.0.7 on 2020-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0005_auto_20200625_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenfile',
            name='lastModified',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examenfile',
            name='lastModifiedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examenfile',
            name='name',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='examenfile',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examenfile',
            name='type',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='examenfile',
            name='webkitRelativePath',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
