# Generated by Django 3.0.7 on 2020-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_auto_20200706_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfile',
            name='lastModifiedDate',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='examenfile',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='examenfile',
            name='type',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='examenfile',
            name='webkitRelativePath',
            field=models.CharField(default='', max_length=500),
        ),
    ]
