# Generated by Django 3.0.7 on 2020-07-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0007_auto_20200706_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenfile',
            name='lastModified',
        ),
        migrations.RemoveField(
            model_name='examenfile',
            name='lastModifiedDate',
        ),
        migrations.RemoveField(
            model_name='examenfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='examenfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='examenfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='examenfile',
            name='webkitRelativePath',
        ),
    ]
