# Generated by Django 3.0.7 on 2020-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0008_auto_20200706_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='examen_type',
            field=models.CharField(choices=[('IRM', 'IRM'), ('Scanner', 'Scanner'), ('Échographie', 'Échographie'), ('Fibroscopie', 'Fibroscopie'), ('Mammographie', 'Mammographie')], default='IRM', max_length=15),
        ),
    ]
