# Generated by Django 3.0.7 on 2020-07-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0009_auto_20200708_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='examen_type',
            field=models.CharField(choices=[('IRM', 'IRM'), ('SCANNER', 'Scanner'), ('ECHOGRAPHIE', 'Échographie'), ('FIBROSCOPIE', 'Fibroscopie'), ('MAMMOGRAPHIE', 'Mammographie')], default='IRM', max_length=15),
        ),
    ]
