# Generated by Django 3.0.7 on 2020-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0011_examen_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='valide',
            field=models.BooleanField(),
        ),
    ]
