# Generated by Django 3.0.7 on 2020-07-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0012_auto_20200709_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
