# Generated by Django 3.0.7 on 2020-07-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0013_examen_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='file',
        ),
    ]
